// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pathways_api.Data;

namespace pathways_api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("pathways_api.Data.Entities.RoleLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("rolelevels");
                });

            modelBuilder.Entity("pathways_api.Data.Entities.RoleLevelRule", b =>
                {
                    b.Property<int>("RoleTypeId");

                    b.Property<int>("RoleLevelId");

                    b.Property<int>("SkillTypeId");

                    b.Property<int>("SkillLevelId");

                    b.HasKey("RoleTypeId", "RoleLevelId", "SkillTypeId", "SkillLevelId");

                    b.HasIndex("RoleLevelId");

                    b.HasIndex("SkillLevelId");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("RoleLevelRule");
                });

            modelBuilder.Entity("pathways_api.Data.Entities.RoleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("rolestypes");
                });

            modelBuilder.Entity("pathways_api.Data.Entities.SkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("skilllevel");
                });

            modelBuilder.Entity("pathways_api.Data.Entities.SkillType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("skilltypes");
                });

            modelBuilder.Entity("pathways_api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("UserLoginId");

                    b.HasKey("Id");

                    b.HasIndex("UserLoginId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("pathways_api.Data.Entities.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Deactivated");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("userlogins");
                });

            modelBuilder.Entity("pathways_api.Data.Entities.UserSkill", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("SkillTypeId");

                    b.Property<int>("SkillLevelId");

                    b.HasKey("UserId", "SkillTypeId");

                    b.HasIndex("SkillLevelId");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("userskills");
                });

            modelBuilder.Entity("pathways_api.Data.Entities.RoleLevelRule", b =>
                {
                    b.HasOne("pathways_api.Data.Entities.RoleLevel", "RoleLevel")
                        .WithMany()
                        .HasForeignKey("RoleLevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("pathways_api.Data.Entities.RoleType", "RoleType")
                        .WithMany()
                        .HasForeignKey("RoleTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("pathways_api.Data.Entities.RoleLevel", "SkillLevel")
                        .WithMany()
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("pathways_api.Data.Entities.RoleLevel", "SkillType")
                        .WithMany()
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("pathways_api.Data.Entities.User", b =>
                {
                    b.HasOne("pathways_api.Data.Entities.UserLogin", "UserLogin")
                        .WithMany()
                        .HasForeignKey("UserLoginId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("pathways_api.Data.Entities.UserSkill", b =>
                {
                    b.HasOne("pathways_api.Data.Entities.SkillLevel", "SkillLevel")
                        .WithMany()
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("pathways_api.Data.Entities.SkillType", "SkillType")
                        .WithMany()
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("pathways_api.Data.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
